baseURL = 'https://viktoraxelsen.github.io/'
title = "Haozhen Zhang - CS Ph.D. at NTU"

# multi-language support
defaultContentLanguage = 'en'

# enable git info
enableGitInfo = true

# disable taxonomy, term and RSS (which removes categories, tags and index.xml)
disableKinds = ["taxonomy", "term", "RSS"]

[module]
  [[module.imports]]
    path = 'github.com/geekifan/zero-academic-page'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = "Haozhen Zhang - CS Ph.D. at NTU"

    [languages.en.params]
      author = "Haozhen Zhang"
      description = "CS Ph.D. student at Nanyang Technological University (NTU) <br><br> Focusing on **LLM/Agent Memory** & **Routers** and their synergy with **Graphs**"
      motto = "**Done is better than perfect**"
    
    [[languages.en.menu.main]]
      name = 'About Me'
      url = '#about-me'
      weight = 1
    [[languages.en.menu.main]]
      name = 'News'
      url = '#news'
      weight = 2
    [[languages.en.menu.main]]
      name = 'Publications'
      url = '#publications'
      weight = 3
    [[languages.en.menu.main]]
      name = 'Educations'
      url = '#educations'
      weight = 4
    [[languages.en.menu.main]]
      name = 'Professional Experience'
      url = '#exp'
      weight = 5
    
    [[languages.en.menu.main]]
      name = 'Professional Service'
      url = '#service'
      weight = 6
    
    [[languages.en.menu.main]]
      name = 'Miscellaneous'
      url = '#miscell'
      weight = 7
    
    [[languages.en.menu.main]]
      name = 'Contact'
      url = '#contact'
      weight = 8
      

[params]
  profilePicture = "images/p2_resize.jpg"
  enableDarkMode = true
  
  [[params.social]]
    name = "github"
    url = "https://github.com/ViktorAxelsen"
    icon = "fab fa-github"
  [[params.social]]
    name = "google-scholar"
    url = "https://scholar.google.com/citations?user=dqOYStwAAAAJ&hl=zh-CN"
    icon = "fab fa-google-scholar"
  [[params.social]]
    name = "email"
    url = "mailto:wazhz14 [AT] gmail [DOT] com"
    icon = "fas fa-envelope"
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/"
    icon = "fab fa-linkedin"
  [[params.social]]
    name = "Twitter"
    url = "https://x.com/haozhen_ntu"
    icon = "fab fa-twitter"

[build]
  writeStats = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
